Fixing oversampling in Bragg2DPtycho
cdtools-developers/cdtools pull request #12
Opened 2024-12-22 16:01 UTC by allevitan

There was an issue with the oversampling parameter in the Bragg2DPtycho model when correct_tilt=True. This should fix it, plus I moved over the object_view_crop stuff from FancyPtycho because it was so useful.

2025-01-04 22:38 UTC, yoshikisd requested changes
The changes you made look good to me. I tested out `Bragg2DPtycho` with `oversampling`, `correct_tilt`, `probe_fourier_crop`, and `obj_view_crop` with AuBalls_700ms_30nmStep_3_6SS_filter.cxi and things are running fine on my machine.

But I did spot a bug where `translation_offsets` is always set to zero within `Bragg2DPtycho`.

2025-01-04 22:38 UTC, yoshikisd commented on src/cdtools/models/bragg_2d_ptycho.py
>          translation_offsets = 0 * (t.rand((len(dataset),2)) - 0.5)
It looks like translation_offsets will always be set to 0. Is this the intended behavior?

2025-01-06 10:34 UTC, allevitan commented on src/cdtools/models/bragg_2d_ptycho.py
>          translation_offsets = 0 * (t.rand((len(dataset),2)) - 0.5)
This is the intended behavior, although the code is clearly a silly/misleading way to do that. At some point there was an option to start the translation offsets != 0 (with a bit of error intentionally introduced) to help with the raster grid pathology. This was a kludge to keep the shape the same, but just set it to zero.

It really should be changed, but it's also in, e.g., FancyPtycho, so I'll make this a separate issue and maybe package it with some other things to tidy up the code. With that, would you be good with merging the pull request?

2025-01-06 17:21 UTC, yoshikisd approved these changes

2025-01-06 17:22 UTC, yoshikisd commented on src/cdtools/models/bragg_2d_ptycho.py
>          translation_offsets = 0 * (t.rand((len(dataset),2)) - 0.5)
That sounds good to me. Let's merge the pull request.

2025-01-06 17:24 UTC, merged